inputDirectory: input
outputDirectory: output
templateDirectory: template
title: My blog
ga: 
theme: MonoChrome
description: some cool line
additionalItems: 
additionalFooterLinks: 
additionalNavLinks: 
facebook:  https://facebook.com
twitter:  https://twitter.com
linkedin: https://linkedin.com
email: test@mail.com
subdirectory: GenesysSSG.Themes.MinimalCache.Demo/